### ISSUE TITLE
Story: As an engineer I want a way to partition an analysis on a subset of nodes within my graph

### ISSUE THREAD

**Issue by kbastani** [kbastani/neo4j-mazerunner#29]
As an engineer I want a way to partition an analysis on a subset of nodes within my graph.

Story detail:

(1) Select a set of nodes by label (A)

(2) Describe a relationship that connects (A) to a set of other nodes (B)

(3) Describe the relationship(s) between the (B) nodes

(4) Dispatch jobs to a queue for each (A) and the pattern that is described in (2) and (3)

(5) The result of each analysis should be stored as a relationship connected between (A) and (B) - (R)

(6) (R) should be updated to include the property for the analysis described in (5)

**Comment by kbastani** [comment]
Implemented in https://github.com/kbastani/neo4j-mazerunner/commit/7d412265a8620dec471f0495e2e9d6da41b8eb35

**Comment by dalanlan** [comment]
Any guide on how to adopt this?
