### ISSUE TITLE
MazeRunner Problems

### ISSUE THREAD

**Issue by machbio** [kbastani/neo4j-mazerunner#31]
Mazerunner does not seem to work for me - here are some of the steps that I have followed..

- I have followed the README.md file of the following github repository : https://github.com/kbastani/neo4j-mazerunner

![docker_ps](https://cloud.githubusercontent.com/assets/1488387/6231113/9934b962-b692-11e4-97cb-880ebe863604.png)

- My Neo4j Data looks like this :   
![neo4j_data](https://cloud.githubusercontent.com/assets/1488387/6231649/ff354bee-b694-11e4-90e6-f07d419ebd0f.png)
![neo4j_rel](https://cloud.githubusercontent.com/assets/1488387/6231652/03da3ccc-b695-11e4-9c0b-809c64b07cdd.png)

- Ran the Curl job 
![curl_job](https://cloud.githubusercontent.com/assets/1488387/6231660/13ab33b8-b695-11e4-8e82-475cc2f46cc2.png)

- Checked the RabbitMq job Queue 
![rabbitmq_jobs](https://cloud.githubusercontent.com/assets/1488387/6231673/265fcac8-b695-11e4-8e15-84a0046adf4c.png)

I do not know much about Spark, but I found that in the following file - 
https://raw.githubusercontent.com/kbastani/neo4j-mazerunner/af6a93c91b9ba54403422eca7756695911e341f1/src/spark/src/main/resources/spark.properties

```
# The relationship type to extract the subgraph from
org.mazerunner.job.relationshiptype=KNOWS
```

So Does the Relationship type limited to KNOWS relationship ??

**Comment by kbastani** [comment]
The `org.mazerunner.job.relationshiptype` is legacy and will be removed soon. 

Can you run the following query?

    MATCH (n)-[:gene_pathway]-()
    WHERE has(n.pagerank)
    RETURN n
    LIMIT 10;

**Comment by kbastani** [comment]
I found the issue. The `kbastani/docker-neo4j:latest` was not correctly merged. https://github.com/kbastani/docker-neo4j/pull/1

The repository is in sync now and the image is rebuilding. Next time I update I will version the images correctly so the issue will be more obvious.

Monitor the build status here: https://registry.hub.docker.com/u/kbastani/docker-neo4j/builds_history/84383/

**Comment by machbio** [comment]
Thank you, I will test it out tonight.. and update you on the issue..

**Comment by kbastani** [comment]
Great. Make sure that you touch the `/service/mazerunner/warmup` endpoint if you have any problems.

**Comment by kbastani** [comment]
Any updates on whether or not this solved your problem?

**Comment by machbio** [comment]
- I did see pagerank property updated on some of the nodes and not every pagerank analytics ran completely due to a SPARK error
- As with the problem, it seemed like a memory issue with Spark, I am trying to configure on EC2 - to check whether the issue is related to Memory 

I do not have the exact error log, but it looked similiar to the error log here - https://issues.apache.org/jira/browse/SPARK-3055

**Comment by kbastani** [comment]
It's almost certainly a memory issue, as Spark is running in standalone mode. There is a partitioned analysis endpoint that allows you to analyze smaller subgraphs if you want to try that. Take a look at http://www.kennybastani.com/2015/01/categorical-pagerank-neo4j-spark.html

Closing this issue.

**Comment by machbio** [comment]
@kbastani Thank you, It works perfectly.. I am a Bioinformatician, so the use case for using the software is quiet different from the software world.. There are different relationships from a node to different type of nodes, hence the analysis tag on the node is being overwritten when the analysis is being done for different types of relationship.. 

Is it possible for you to document your extension (spark) and the algorithm for me to be able to modify to my own needs from maze runner..

**Comment by kbastani** [comment]
Happy to help. Sure, please create an issue stating the needs or what you find inflexible and I'll be sure to prioritize it in the roadmap.
